### ISSUE TITLE
Memory (RAM) management

### ISSUE THREAD

**Issue by jpeelle** [rhodricusack/automaticanalysis#100]
I have an analysis that's crashing my 8GB laptop during fMRI model estimation. I think there's a maxmem flag that might help with this—can someone remind me where?

**Comment by tiborauer** [comment]
Do you mean SPM flag defaults.stats.maxmem?

https://en.wikibooks.org/wiki/SPM/Faster_SPM

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham Hill
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D04F5F.0CADAB60]+44-1784-27-6594
[cid:image002.jpg@01D04F5F.0CADAB60]Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>

[royalhollowaylogo]<https://www.royalholloway.ac.uk/psychology/home.aspx>

**Comment by jpeelle** [comment]
Yes, thanks! I thought this would help

aap.spm.defaults.stats.maxmem = 2^10; % default 2^28

but it didn't. In fact it was in aamod_firstlevel_contrasts—the efficiency estimation seemed to be causing things to choke. Setting aap.tasksettings.aamod_firstlevel_contrasts.estimateefficiency to 0 fixed this.

**Comment by tiborauer** [comment]
It is actually not the efficiency estimation but the distribution sampling (img2hist/wilcoxon/Hodges-Lehman estimate) causes the issue.
