### ISSUE TITLE
Two versions of meminfo.m in v5-devel

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#109]
I recently noticed there are now two versions of meminfo.m in the v5 development distribution -- one in extrafunctions and one in external (I think the one in external is new).

Is this intentional? aa will use the file it finds first in the path.

An added complication: Neither of these work for us under OS-X. They both assume files in /proc which doesn't exist under Darwin.

Thoughts?

**Comment by tiborauer** [comment]
There is no meminfo.m in https://github.com/rhodricusack/automaticanalysis/tree/v5-devel/external! My commit has removed that one for the very same reason you just mentioned.

You are right about OSX! These are linux-only functions. I have never used OSX and neither have access to it, so I cannot develop for it. I guess there are other features which may not work under OSX. It is something maybe you could implement.

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham Hill
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D04F5F.0CADAB60] +44-1784-27-6594
[cid:image002.jpg@01D04F5F.0CADAB60] Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>

[royalhollowaylogo]<https://www.royalholloway.ac.uk/psychology/home.aspx>
