### ISSUE TITLE
Can we change the aa engine to make streams renameable by default?

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#113]
Hello all,

Is there a reason the default aa behavior is for a stream to be _not_ renameable?

Yes, I realize renaming a stream can break things, but it's not like you can do it accidentally. 

I'm often finding the need to rename a stream to customize a module for some application and it feels silly to edit/add/commit/push/pull-request an isrenameable=1 tag to an xml header just so I can use aas_renamestream( )...

Thoughts?

**Comment by tiborauer** [comment]
Hi,

Not every module supports stream renaming, especially outputs are „sensitive”. Sometimes, further actions are also needed to preserve pipeline consistency (e.g. ROI modules). Therefore, unfortunately, a simple switch of flag is not enough in most cases.
We could, perhaps, go through modules to see which one supports stream renaming out of the box, and which one requires a minimum rewriting.

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham Hill
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D2338B.1F3C9360] +44-1784-27-6594
[cid:image002.jpg@01D2338B.1F3C9360] Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>

[royalhollowaylogo]<https://www.royalholloway.ac.uk/psychology/home.aspx>

**Comment by jones-michael-s** [comment]
Hi Tibor,

> Not every module supports stream renaming, ....

Does this mean a module can be _broken_ by adding an isrenameable=1 tag to the xml (and subsequently renaming the stream)? That's not a possibility I had considered. I assumed names are arbitrary, as long as you rename the stream everywhere it appears.

M

**Comment by tiborauer** [comment]
Hi,

Most/Certain modules uses hardcoded stream names in the body (i.e. the m-file). If the body looks for an input stream e.g. “inpstream1” (i.e. hardcoded in the body) and you specify and use “inpstream2” in the header (xml), then the module will not find the input and it will crash. If the body writes out an output stream e.g. “outstream1” (i.e. hardcoded in the body) and you specify and use “outstream2” in the header (xml), then the module will not write out “outstream2” and the module looking for it will crash.

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham Hill
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D04F5F.0CADAB60] +44-1784-27-6594
[cid:image002.jpg@01D04F5F.0CADAB60] Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>

[royalhollowaylogo]<https://www.royalholloway.ac.uk/psychology/home.aspx>
