### ISSUE TITLE
VmSwap in meminfo.m

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#116]
Hello all,

I'm trying to port (the new) meminfo.m to OS X. I've figured out how to obtain all the fields returned in M except for one: "SwapUsedBy" (i.e., VmSwap in /proc/pid/status -- mac unix doesn't use a /proc directory).

Might anyone know how to find VmSwap under OS X? Failing that, might it be the case that we really don't need the M.SwapUsedBy field? It doesn't look like anything in the distribution that calls meminfo uses it.

Mike

**Comment by tiborauer** [comment]
SwapUsedBy is not used by any function. It has been added only for the sake of comprehensiveness.

**Comment by jones-michael-s** [comment]
Hi Tibor,

Thanks for the info. What I will do is set the  M.SwapUsedBy to zero on the OS X implementation and display a warning using aa_log (just in case some caller of the code tries to use the field in the future).

Mike
