### ISSUE TITLE
A proposed change to aaq_qsub

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#123]
Hello all,

We finally have aa running on our cluster!

I’m now cleaning up a few odds and ends. I would like to make a small change to aaq_qsub.m. 

Before a job is submitted, aaq_qsub adds the local paths to J.AdditionalPaths (or to J.PathDependencies on pre-R2013a Matlab). This works nicely on setups that have a shared filesystem. However, our cluster does not, so these paths are unhelpful. They don’t break anything, but all our cluster log files get filled with many (many) warnings about nonexistent directories. 

As such, I would like to make adding these paths to the job optional. However, I don’t want to break current installations, so the default behavior will be to add the paths and the user must explicitly opt out. Something like:

`if (~isfield(aap.directory_conventions.qsub, ‘doNotAddLocalPathsToJob’) ||`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`aap.directory_conventions.qsub.doNotAddLocalPathsToJob == false) `
` `
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              ` if isprop(J,'AdditionalPaths')`
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                  ` J.AdditionalPaths = aacache.path.reqpath;`
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;               `elseif isprop(J,'PathDependencies')`
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                  `J.PathDependencies = aacache.path.reqpath;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;				`end`
` `
`end`

By checking if the aap field exists, current users would not even have to modify their parameter files. Only if you want to opt-out (like we do) would you add a line:

            <doNotAddLocalPathsToJob>true</doNotAddLocalPathsToJob>

to your parameter file in the qsub section.

Does that seem like a reasonable change? I should note I’ve tried other solutions like customizing our local cluster interface code to remove the paths, but once the job is passed to submit( ), Matlab won’t let you to modify the job structure.

Thanks much,
Mike

**Comment by tiborauer** [comment]
Is not there a way in MATLAB to detect whether shared file system is used?

**Comment by jones-michael-s** [comment]
The problem is a little tricker (at least for us) -- the issue isn't whether there is a shared file system; it's whether cluster Matlab can use aa where it is installed on the local machine. Our cluster cannot, even though we mount the cluster file system on the local machine.

I can't think of a solution other than a flag in aap that covers all possibilities.

**Comment by tiborauer** [comment]
It work for us at both sites (CBSU and RHUL).

**Comment by tiborauer** [comment]
Do you want to make a PR?

**Comment by jones-michael-s** [comment]
I'll do a PR.

Any thoughts on memoryBase and timeBase?

**Comment by tiborauer** [comment]
Keep in mind that @dprice80 also submits/submitted a PR on aaq_qsub. You can maybe ask him to incorporate the proposed changes, so we can test them in one step.

**Comment by jones-michael-s** [comment]
Will do.

Any thoughts on memoryBase and timeBase?

**Comment by tiborauer** [comment]
How do you want to use them?

**Comment by jones-michael-s** [comment]
I would like to use them as multipliers to adjust  walltime and memory for each submitted job based on the values listed in the module header (for module that have defined them).

It looks like this is what they were designed to do, but then they got commented out of the aaq_qsub. My testing shows that every job I submit to the cluster gets a walltime of whatever is specified in aap.aaparallel.walltime and a memory of whatever is listed in aap.aaparallel.memory. Yet, different modules have wildly  different time and memory requirements (autoidentify vs. normalization, to name but one example).

This functionality seems like a great idea -- was it moved elsewhere in the code and I'm simply not seeing it?

**Comment by tiborauer** [comment]
Yes, it is correct. My question was wrongly phrased. I meant **how** that how do you want to implement it.
It varies between scheduler to scheduler (TORQUE, SLURM, SoGE), how it accepts these parameters.

Feel free to experiment with it!

**Comment by jones-michael-s** [comment]
> It varies between scheduler to scheduler (TORQUE, SLURM, SoGE)...

I'm new to cluster programming, so there are certainly issues I don't understand fully. However, I'll play around with aaa_qsub and once I have a something that works nicely for us, I'll show what code changes I made in a new issue and perhaps people can comment on whether it's a good general solution.
