### ISSUE TITLE
remove multi echo output streams in aamod_convert_epis?

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#125]
Hello all,

aamod_convert_epis.xml defines a collection of echo output streams (echo1, echo_2, ... echo_1_1, echo_1_2 .. etc).

Would it be possible to put these in a new header (say, aamod_convert_epis_multiecho.xml) and delete them from  aamod_convert_epis.xml? We've had to comment them out since forever to use the module because all they do is make reporting complain, at least on our data.

Mike

**Comment by tiborauer** [comment]
Again, are you sure that you use the correct version? I never have reporting issue due to them.

**Comment by jones-michael-s** [comment]
Ah, that explains it (the person in our lab who brought this to my attention was running v5-stable. The current repo does not produce this error.)
