### ISSUE TITLE
What is the correct way to use aa_export_toBIDS?

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#128]
Hello all,

We’ve recently started experimenting with aa_export_toBIDS. We’re trying to use the function as a stand-alone tool, calling it from the command line like so:

> aa_export_toBIDS(aap, ’/directory/to/put/results’);

where aap is the aap struct of our just-completed analysis. 

Unfortunately the code crashes almost immediately (aa_export_toBIDS calls aas_setcurrenttask, which is looking an “internal” field in the aap struct, which doesn’t exist).

I suspect our usage is wrong. Can anyone explain how to use aa_export_toBIDS correctly? 

Thanks much,
Mike

**Comment by tiborauer** [comment]
You need to load in the aap structure from the mat-file stored in the study folder.

**Comment by tiborauer** [comment]
Alternatively, if you are in the study folder, you do not have to specify aap, because the function will load in aap.

**Comment by jones-michael-s** [comment]
I assume this is aap_parameters.mat?

**Comment by jones-michael-s** [comment]
Oops -- never mind (I just looked at the code and obviously it's aap_parameters.mat).

I'll pass this along to our student who is working on this. Thanks!

**Comment by tiborauer** [comment]
Yes! I should have also probably said that! :)

**Comment by jones-michael-s** [comment]
Hey, we just tried it and it worked great!

FYI
