### ISSUE TITLE
Restarting a failed analysis after removing one or more subjects?

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#130]
Hello all,

We're currently working on an 82-subject analysis. Segmentation works on 80 of the subjects then crashes on the last two for some reason. Rather than trying to figure out why, I'd like to just remove these two subjects and finish the rest of the analysis (we can live with only including 80 subjects in the study).

So I comment out the aas_addsubject in my script for these two subjects and also 4 related aas_addinitialstreams (this is stage 2 of a two-part analysis, and I'm defining a T1 and a T2 input for each subject that come from  a previous analysis). I delete these two subject directories from aap.directory_conventions.rawdatadir. I do a clear and clear functions in Matlab.

When I restart the job, aa continues to look for 82 subjects (and crashes).

Is there some other files I need to delete? Something else to clear? 

If this was a smaller dataset, I would just delete the entire results directory (i.e., aap.directory_conventions.analysisid) and restart from scratch, but segmentation on this takes days to finish on our cluster, so that's not an attractive option.

I'm currently combing though the scheduler code trying to figure out where aa is still getting 82 subjects from, but right now I'd really just like to get the analysis finished. 

Thanks for any tips,
Mike

**Comment by tiborauer** [comment]
What do you mean “restart the job”? If you mean job on the scheduler, then the aap structure is not changed, so it will search for the original 82 subject. You have to rerun the UMS to update aap and resubmit the jobs.

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham Hill
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D04F5F.0CADAB60] +44-1784-27-6594
[cid:image002.jpg@01D04F5F.0CADAB60] Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>

[royalhollowaylogo]<https://www.royalholloway.ac.uk/psychology/home.aspx>

**Comment by jones-michael-s** [comment]
Yes, by "restart the job" I mean I rerun my Matlab script (like I would if I were running the analysis for the first time). 

When we've restarted an analysis part way in the past, we find aa is very good about checking what stages have been run and continuing from where it left off. The odd thing about our current situation is we've deleted two subjects that were in the previous run. This seems to be confusing aa.

**Comment by tiborauer** [comment]
Is not it possible that these subjects have been somehow added? Have you checked the aap.acq_details.subjects right before aa_doprocessing?

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham Hill
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D04F5F.0CADAB60] +44-1784-27-6594
[cid:image002.jpg@01D04F5F.0CADAB60] Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>

[royalhollowaylogo]<https://www.royalholloway.ac.uk/psychology/home.aspx>

**Comment by jones-michael-s** [comment]
Found a solution! 

I went into ~/.aa and deleted all of the old worker files.

I don't know if that will create other problems later, but at least aa stopped looking for the two deleted subjects...

Someday somebody should document all these kinds of tricks :-)

**Comment by tiborauer** [comment]
I do not think that deleting those files had an impact, but rather that the aap was correctly updated this time. So my guess is, it was just a "clean" restart. But we will never know, unless you try deleting further subjects...
