### ISSUE TITLE
New qsub will not resubmit the last job when failed

### ISSUE THREAD

**Issue by tiborauer** [rhodricusack/automaticanalysis#135]
Hi @dprice80,

I have noticed a strange behaviour in your solution: If the last job is failed, aa will finish the pipeline as completed ("all job done", garbagecollection, closing jobs). There is no final pipeline crash. The only clear indication is the pop-up window with the error message; and, of course, the error message in the command window, but only if you scroll back, which you would not do if the pipeline is marked completed.
However, these error messages also occur when the job is resubmitted and eventually completed. That was my first thought, as well. I became suspicious when I could not find the folder of the last module, which was deleted, when the error was detected.

**Comment by dprice80** [comment]
Do you mean if the very last job in the queue fails? i.e. if I have 10 jobs to run, and there is an error in job 10, then the script will display the error message, but not crash. But if there is an error in job 9 then the script will crash correctly.

**Comment by tiborauer** [comment]
Yes

Vale,

Auer, Tibor ('99 Ph)

**Comment by dprice80** [comment]
Okay, I will run a test and get back to you. I'm sure there will be an easy fix to that. It's probably something to do with obj.jobnotrun not being set correctly.

**Comment by jooh** [comment]
This all fixed in the current release 2ed6c784b0d83e63a30b64aa4231badb6bbff323, right? If so, please close.
