### ISSUE TITLE
Error reading BIDS data from OpenFMRI

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#139]
Hello all,

Our lab has used aas_processBIDS in the past, which has worked very nicely. 

However, we’re currently trying to use a dataset we downloaded from openfmri (specifically, the resting state data at https://openfmri.org/dataset/ds000224/).

aas_processBIDS cannot parse this data.

The problem appears to be directory structure in ds000224 does not conform to the BIDS standard (at least not as described in https://www.nature.com/articles/sdata201644).

aa expects something like

my_dataset/sub-01/anat/<files>
my_dataset/sub-01/func/<files>
my_dataset/sub-02/anat/<files>
my_dataset/sub-02/func/<files>
etc

ds000224 is organized like

my_dataset/sub-01/sess-func01/func/<files>
my_dataset/sub-01/sess-func02/func/<files>
my_dataset/sub-01/sess-struct01/anat/<files>
etc

Yet, openfmri claims ds000224 is BIDS compliant (I ran it through their validator). Is this a change to the BIDS standard that aa doesn’t understand? Is there an option in aap I need to set? Is there some tool I need to use to rearrange this into the kind of BIDS aa understands?

Thanks for any help,
Mike

**Comment by jooh** [comment]
I think that is in fact a bids-compliant format. You need to set the sessnames input argument, e.g. {'func01','func02','struct01'}. If you then want to model all the data as if it came from the same session, set aap.acq_details.input.combinemultiple = 1.

**Comment by jones-michael-s** [comment]
Hi Johan,

Specifying session names put us on the right track. We can now get aa to read in the structural, but the functionals are having problems with the fieldmaps:

1) aa expects the fieldmap json(s) to be in the same directory as the fieldmaps (see line 202). This is not the case for this data -- there is a single copy of each fieldmap json  at the top level directory (presumably these apply to all fieldmaps in the data). I could easily modify aas_processBIDS to look for the top level maps if it doesn't find any in the fmap folder, but before I start rewriting code I'll first ask if there's an option, flag, or parameter that tells aa to do this already?

2) aa understands "phasediff", "phase1", and "fieldmap" ftypes (see switch statement line 212). The fieldmaps in this dataset are of type phasediff, magnitude1, and magnitude2. Any suggestions on how to handle magnitude1 and magnitude2 fieldmaps?

Mike

**Comment by tiborauer** [comment]
Hi,

 

1.

JSONs does not have to be at the lowest level. aa is able to handle JSONs from the higher level, too. Subfunction retrieve_file check higher levels, if file not found in the same folder.

 

2.

You can leave both files there. If you check aas_addsubject, it also mentions three files (two magnitudes and one phasediff). aamod_fieldmap2vdm discards the second, though.

 

Vale,

Tibor

 

Auer, Tibor (Ph ’99)

**Comment by jones-michael-s** [comment]
Hi Tibor,

Thanks for the follow-up.

> JSONs does not have to be at the lowest level. aa is able to handle JSONs from the higher level, too. Subfunction retrieve_file check higher levels, if file not found in the same folder.

I see calls to retrieve_file in the processing of structural (line 159), functional (line 249), and diffusion (line 167), but not in the processing of fieldmaps. Perhaps this was an oversight? Is there a more recent version of aas_processBIDS available?

> You can leave both files there. If you check aas_addsubject, it also mentions three files (two magnitudes and one phasediff). aamod_fieldmap2vdm discards the second, though.

Alas, the issue is not that aas_addsubject doesn't understand the fieldmaps, its that the switch statement in aas_processBIDS doesn't include them. This leaves the variable fmap undefined, which then crashes the horzcat statement on line 225. Again, might there be a more recent version of aas_processBIDS available? I could modify it myself, but BIDS and fieldmaps are rather outside my wheelhouse.

Mike

**Comment by tiborauer** [comment]
Hi Mike,

 

1.

You are right! I actually even put a note about the assuption. 😊 Yes, I think, retrieve_file should be implemented there, as well. I am not sure why I have not done it.

 

2.

But it should! When phasediff is detected, all files with the same name but different suffix will be included by line 220, so fmap.fname will be a 1x3 string cell with the three filenames.

 

Vale,

Tibor

 

Auer, Tibor (Ph ’99)

**Comment by jones-michael-s** [comment]
OK, so I moved the jsons down into the fieldmap directory in my data and re-ran the analysis and it (mostly) worked. When aas_processBIDS found the phasediff fieldmap, it indeed also found the two magnitude fieldmaps, then added all three in addsubject.

The only snag was that I had to move fieldmapimages = horzcat(fieldmapimages,fmap); _inside_ the phasediff case. (The other cases don't generate an fmap for it to horzcat).

I think that modification (and adding a retrieve_file to the fieldmap section) will put things right. Would you like to add the fix? I'd do it, but my last PR is still waiting for me to change the LI toolbox stuff (which I promise I'll get to as soon as I crawl out from under the mountain of deadlines we're up against :-)

**Comment by tiborauer** [comment]
I cannot see how your modification matters in your case (phasediff + magnitude(s)), because it is executed anyway; however, it will be an issue in the other cases. You are right, that they do not create fmap at the moment, because they are not yet fully implemented. They are placeholders for such cases, when fieldmaps are not in the common Siemens format you are also using.

 

Vale,

Tibor

 

Auer, Tibor (Ph ’99)

**Comment by jones-michael-s** [comment]
> I cannot see how your modification matters in your case (phasediff + magnitude(s)), because it is executed anyway;

If "phasediff" was the _only_ json in the directory, then my suggested modification would not matter. However, when the code encounters "magnitude1" or "magnitude2" it doesn't know what to do with them. So the switch bounces, fmap is left undefined, and horzcat crashes. The code needs to know it can ignore these. That's what my modification accomplishes. By moving horzcat inside phasediff, the other cases can stay as they are, but the function will still work.
