### ISSUE TITLE
RFC: Module options in provenance graphs.

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#140]
Hello all,

I've been experimenting with adding module information to the nodes in provenance maps. Here's an example:

![spm_tutorial_prov](https://user-images.githubusercontent.com/25826038/33090557-effcb7bc-ceb9-11e7-8117-42fde79ad9ce.jpg)

I show scalar options and strings -- vectors I truncate (because they can be very large).

Any thoughts? Would this be useful? If so, should it be the default or should it be an aap option? Are there ways to make it better?

Cheers,
Mike

**Comment by tiborauer** [comment]
Hi,

 

NIDM Workflow aims to develop and more standard and formalised  (based on PROV-One) representation of the processes (i.e. modules) and settings:

https://docs.google.com/document/d/1OjdvKyjSuLXoPrmH18SPj2Fe1bvkomQjowY7TG-F8MQ/edit

aa_provenance.m <https://github.com/rhodricusack/automaticanalysis/blob/master/aa_toolbox/provenance/aa_provenance.m>  is an attempt to implement NIDM-W in aa.

 

I recommend you to continue aa_provenance accordingly. I am also happy to invite you to NIDM-W, if you are interested.

 

Vale,

Tibor

 

Auer, Tibor (Ph '99)

**Comment by jones-michael-s** [comment]
Interesting. I didn't realize provenance was a standard; I assumed it was just an aa tool.

We'll continue to use my expanded format locally (it's already been helpful in flushing out a few aa bugs) but I'll leave it out of the distribution.

Mike
