### ISSUE TITLE
3D nifti crashes tsdiffana

### ISSUE THREAD

**Issue by jooh** [rhodricusack/automaticanalysis#142]
This came in from a user:

```
Error using strrep
Input strings must have one row.

Error in spm_fileparts (line 18)
if ~ispc, fname = strrep(fname,'\',filesep); end

Error in run_tsdiffana (line 11)
                     [p f e] = spm_fileparts(job.imgs{k}{1});

Error in aamod_tsdiffana (line 27)
         run_tsdiffana('run','timediff',job);
```

We worked around the crash by setting aap.options.NIFTI4D = 1. tsdiffana should probably be fixed to restore 3D nifti support.

Beyond that, should we change the defaults to 4D nifti given that we're all using it now? Should we even deprecate 3D nifti? Supporting 2 different file formats seems taxing unless there are use cases that can only be supported with 3D nifti.

**Comment by tiborauer** [comment]
I guess the core function timediff supports 3D NifTI, so the only issue is the spm_fileparts. I think it is an easy fix ( deblank(job.imgs{k}{1}(1,:)) ).

**Comment by tiborauer** [comment]
Solved in my repo in [this commit](https://github.com/tiborauer/automaticanalysis/commit/74441c38fd0960bd64ddb7150b27be9b70be4570)

**Comment by jpeelle** [comment]
Add to next pull request?

**Comment by tiborauer** [comment]
Yes, it is part of it.
