### ISSUE TITLE
Cleaning up the first level modules

### ISSUE THREAD

**Issue by jooh** [rhodricusack/automaticanalysis#146]
Here is a listing of all the variants of first level model available in AA. Are any of these suitable for removal?

**Standard AA**
*I don't think anyone is proposing axing these*
aamod_firstlevel_contrasts
aamod_firstlevel_model

**Johan's custom granular AA first level modules**
*model 1-3 replaces aamod_firstlevel_model with a more granular approach. This enables customisation of the model before convolution - see collapsepredictors and subrunsplit, which would typically be added in between stages 1 and 2. Additional examples are available in [my custom AA repo](https://github.com/jooh/pilab_aa).*
aamod_firstlevel_model_1_config
aamod_firstlevel_model_2_convolve
aamod_firstlevel_model_3_estimate
aamod_firstlevel_model_collapsepredictors
aamod_firstlevel_model_subrunsplit 

**Are any of these suitable for removal or significant updating?**
*Authors here are mainly @alexvicegrab @rhodricusack @conorwild and @jpeelle* 
aamod_firstlevel_model_MVPaa.m
aamod_firstlevel_model_MVPaa.xml
aamod_firstlevel_model_nodicom.xml
aamod_firstlevel_model_nodicom_MVPaa.xml
aamod_firstlevel_modelestimate.xml
aamod_firstlevel_modelestimate_saveresids.xml
aamod_firstlevel_modelspecify.m
aamod_firstlevel_modelspecify.xml
aamod_firstlevel_modelspecify_explicitmask.xml

**Comment by tiborauer** [comment]
I think we should delete the followings:
aamod_firstlevel_model_nodicom.xml
aamod_firstlevel_model_nodicom_MVPaa.xml
aamod_firstlevel_modelestimate.xml
aamod_firstlevel_modelestimate_saveresids.xml
aamod_firstlevel_modelspecify.m
aamod_firstlevel_modelspecify.xml
aamod_firstlevel_modelspecify_explicitmask.xml

**Comment by jooh** [comment]
Addressed by recent merge 2ed6c784b0d83e63a30b64aa4231badb6bbff323

Feel free to re-open if you think of more modules that could be removed.
