### ISSUE TITLE
ROI extract - zero_vox

### ISSUE THREAD

**Issue by tiborauer** [rhodricusack/automaticanalysis#152]
I have noticed a potentially serious bug in roi_extract, line 158, which removed zero/NaN voxels from the ROI:
` f = setdiff(f,zero_vox);`

However, f is an index of spatial location (i.e. in a range of 1 and numer of voxels of the image), while zero_vox is a logical array (i.e. 0s and 1s). Consequently, the given code removes only the 1st voxel (if selected by the ROI) regardless whether it is zero/NaN.

Luckily, the solution is simple, because zero_vox corresponds to f:
`f(zero_vox) = [];`

**Comment by tiborauer** [comment]
The effect of the bug is that no voxel is removed from the ROI (the 1st location of the image is usually a corner) and therefore 'contaminated' ROI ends up NaN.

**Comment by jooh** [comment]
I believe this code was originally from @RikHenson. Sounds like a straightforward fix to me. Do you want to add it to the current PR?

**Comment by jooh** [comment]
Fixed in current version.
