### ISSUE TITLE
Flip epi left/right in some subjects?

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#154]
Hello all,

I'm working with a data set that measured motor activation when using the dominant hand in a group that includes a mix of left-handed and right-handed subjects. I need to flip the lefty epis R/L to do a second level analysis. Is there aa functionality for this? My searches turned up nothing.

It's not hard to implement, but perhaps someone already did so somewhere...

Thanks,
Mike

**Comment by jpeelle** [comment]
It actually is a bit tricky because of the left/right asymmetry so I think
most people build a symmetrical template and normalize to that before
flipping. (“Most people” = the few people I talked to in 2010 who were
trying this). (They may not have done this for the dataset you are trying
to replicate though, so maybe it doesn’t matter.)

**Comment by tiborauer** [comment]
We also did something similar for VBM in this article: https://doi.org/10.1002/hbm.23023

We could come up with a module similar to dartel_creattemplate to build a symmetrical template and normalise data to it.

 

Vale,

Tibor

 

Auer, Tibor (Ph '99)

**Comment by jooh** [comment]
I believe there is a symmetrical version of fsaverage, if you'd consider going surface based... No AA implementation of this yet though, I don't think.

**Comment by tiborauer** [comment]
I think the existing dartel_createtemplate could be used to create symmetric template by adding all subjects twice (flipped and upflipped).
Then after aamod_norm_write_(cons)_dartel, EPI/contrast images should be symmetric (?), so we only have to flip them for the second level analysis. I would recommend normalising the contrast images.
