### ISSUE TITLE
aa_config

### ISSUE THREAD

**Issue by tiborauer** [rhodricusack/automaticanalysis#157]
- These configuration specialisations should be turned into parameter set XMLs.
- aas_configforSPM12 could be part of aarecipe and automatically run if SPM12 is detected.

**Comment by jooh** [comment]
I will move aas_configforSPM12 into aarecipe to run with the other SPM-specific stuff.

Is there some other aa_config stuff you are referring to in addition to this?

**Comment by tiborauer** [comment]
The other site/project-specific configuration specialisations should be turned into parameter set XMLs.

**Comment by jooh** [comment]
Ok, after grepping around I can't find any references to any of the functions inside the aa_config directory anywhere. I think this might be more legacy code. Any objections before I remove the entire directory from the project? @jpeelle @rhodricusack ?

I will also get rid of aas_configforSPM12. All the changes it makes can be handled more generally in my devel version by a) defaulting to the correct T1template path for SPM12 in aap_parameters_defaults.xml (I think we've already broken compatibility with older SPMs anyway), b) using a fancy new method to automatically turn the SPM-relative path into the correct absolute path for modules with the tpm setting (more on this later :)). 1 less boilerplate line in the user recipes...

**Comment by tiborauer** [comment]
aa_config functions may or may not be legacy code. They are not referenced, because they have been used by the users to customise parameter defaults. After I implemented the inherited XMLs for the same purpose, they may be obsolete but @jpeelle and @rhodricusack may still use them.

**Comment by tiborauer** [comment]
+1 for the "less boilerplate line in the user recipes" :)

**Comment by jpeelle** [comment]
I don’t use them…

**Comment by tiborauer** [comment]
How about @rhodricusack ?

**Comment by tiborauer** [comment]
I think we agreed to remove them.
@jooh, Could you add this to your (upcoming) PR?

**Comment by jooh** [comment]
Yes, this will be included.

**Comment by jooh** [comment]
Gone in #161 . Let's discuss further there.
