### ISSUE TITLE
Cleaning up old code - examples, aa_test, strjoin

### ISSUE THREAD

**Issue by jooh** [rhodricusack/automaticanalysis#160]
I'm currently working on updating the scripts under examples. The long term goal of this is automated testing, including at least some scripts that can be run outside CBU (finally!).

I have come across a few example scripts that look pretty old. Would it be safe to remove these?

aap_tasklist_begin.xml
aap_tasklist_diffusionFSL.xml
aap_tasklist_end.xml
aap_tasklist_fmri_ppi_fromnifti.xml
aap_tasklist_meg_epochs.xml
aap_tasklist_rsfcMRI.xml
aa_user_diffusionFSL.m
aa_user_macforaws.m
aa_user_meg_aap_testinv2.m
aa_user_meg_aap_test.m
aa_user_meg_aap_test_rhodri.m
aa_user_onaws.m
BIDS114_test1_aa.xml

Relatedly, under aa_testcode there is an old test which seems useful but appears to use a lot of functionality we agreed not to attempt to support at the moment (hyper-alignment). I would like to remove this but even better would be if someone wants to write a new similar test that doesn't require hyper-alignment. In general we need more unit tests (ie tests of individual bits of AA functionality rather than running entire test user scripts).

aatest_dependencies.m

Finally, Matlab includes a strjoin function in recent versions, so it's time for us to get rid of the function by the same name (but slightly different behaviour!) that we ship with AA.

**Comment by tiborauer** [comment]
I would like to keep aap_tasklist_fmri_ppi_fromnifti.xml, because it demonstrates how you can run PPI. I have written it for a project, so the data may not be available for sharing. Therefore, I may need to repuprose it for the 'offical' aa-demo data.  

I am not so sure about testing individual functionalities rather than pipelines. I expect most (if not all) functionalities work in an isolated 'testbed', but issues usually arise from interaction between functionalities. The main stregth of aa is to deal with the interaction, so the users do not have to.

strjoin has been introduced in R2013a; so I agree that we can switch to it.

**Comment by jooh** [comment]
re the PPI tasklist, that sounds like a very useful thing to cover with our examples. But I don't think there is a user recipe for that tasklist in the repo. Maybe better to remove it for now and reintroduce it later in a new user script that uses AA demo or DS114?

The problem with our 'integrated' tests at the moment is that they are exceedingly slow to run. It would be quite useful to have something a lot more light-weight (perhaps using dummy data). You can then start by testing your changes against this, and iterate more quickly on your own development version. Obviously you still want to run the big tests now and then too.

**Comment by tiborauer** [comment]
It seems that you want to strip off the last ounces from aa. :) Certainly, I can keep the working copy of the tasklist and we will see.

I am not sure what "exceedingly slow" means to you, but I remember discussing about it and you used serial execution of the tests, which is, indeed, slow. If you come up with the automated testing, then these tests could be perhaps also executed in parallel.

**Comment by jooh** [comment]
It's easy to check out a previously deleted file later if you want to re-add it, see e.g.

https://hibbard.eu/how-to-restore-a-previously-deleted-file-from-a-git-repository/

Believe it or not, but some large-ish projects have tests that run in a minute or two! Ours take about a week at the moment. Parallelising will help to some extent, but probably won't make the process faster than a day since some modules take several hours to run.

**Comment by jooh** [comment]
All resolved in #163 which is now merged.
