### ISSUE TITLE
Truncated outfile naming in aamod_epifromnifti

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#167]
Hello all,

In aamod_epifromnift, there is the following code

>        
        if isfield(aap.options, 'NIFTI4D') && aap.options.NIFTI4D
            finalepis = finalepis{1};
            ind = find(finalepis=='-');
            sfx = '';
            if isempty(ind),
                ind = find(finalepis=='.');
                sfx = '_4D';
            end
            ind(2) = ind(end);
            finalepis = [finalepis(1:ind(2)-1) sfx '.nii'];
            if iscell(V), V = cell2mat(V); end
            spm_file_merge(char({V(numdummies+1:end).fname}),finalepis,0,DICOMHEADERS{1}.volumeTR);
        end

I'm wondering about the decision to truncate the output filename at the last hyphen.

For example, in ds000102 (openNeuro.org) there are two sessions named run-1 and run-2. Each session is a collection of 146 3D nifti files. I'm using aamod_epifromnift to merge each of these collections into a single 4D nifti file.

I expected aamod_epifromnifti would merge them as:

> sub-01_task-flanker_run-1.nii
> sub-01_task-flanker_run-2.nii

Instead, the module truncates at the the final hyphen and creates:

> sub-01_task-flanker_run.nii
> sub-01_task-flanker_run.nii

I now have two different epi files in my analysis with the same filename. 

Is this the intended behavior? It seems like the sort of thing that is asking for trouble (indeed, it might be related to #165).

Regards,
Mike

**Comment by tiborauer** [comment]
I am not sure about it. I think it might have been there to correspond [line 83](https://github.com/rhodricusack/automaticanalysis/blob/02904fe21c77ecda53e437d65a2443b111ef4309/aa_modules/aamod_epifromnifti.m#L83), but then, it should be "_" rather then "-".

**Comment by jooh** [comment]
I fixed this once in a failed merge attempt, years ago. I agree that it's pretty ugly.

Unfortunately I seem to have lost the fixed version, but basically I just took all the 3D file names, converted to char array, and looked for shared characters across the rows. You can basically create the 4D file name by taking the unchanging characters from the 3Ds (so you strip off the volume numbers). Wish I had managed to keep that change...

**Comment by tiborauer** [comment]
Ad 1.: underscore + file number comes from the SPM file split when rearranging volumes
Ad 2.: I am not sure what you mean. Nothing seems to be stripped off. 
Ad 3.: hyphen in filenames come from the BIDS specification.

**Comment by jones-michael-s** [comment]
> Ad 1.: underscore + file number comes from the SPM file split when rearranging volumes

Since aamod_epifromnift uses SPM, it sounds like we can indeed assume the names in file collections with be _underscore + file number_ at this juncture. As such, it seems to me your suggested fix is a good idea.

> Ad 2.: I am not sure what you mean. Nothing seems to be stripped off.

I meant the way aamod_epifromnifti currently works (i.e., terminating the filename at the last hyphen). It just seemed arbitrary and I was grasping at an explanation.

> Ad 3.: hyphen in filenames come from the BIDS specification.

Be that as it may, _don't use hyphens in filenames_ is Unix 101. They can get parsed as command switches, or as an alias for stdout. Python can confuse them with minus signs. I also seem to recall fixing aa bugs that were triggered by this.

**Comment by tiborauer** [comment]
Am I right to say that the suggested fix (underscore instead hyphen) solves the issue? Or do you (or @jooh) want to implement a more clever solution as outlined by @jooh?

**Comment by jones-michael-s** [comment]
I've changed line 132 in aamod_epifromnifti (jooh's PR repo) as follows:

`OLD: ind = find(finalepis=='-');`
`NEW: ind = find(finalepis=='_');`

and have run about a half dozen analyses without problems.

If group opinion is this is a solid fix, I say go for it.

**Comment by tiborauer** [comment]
I have tried to implement [Johan's solution](https://github.com/rhodricusack/automaticanalysis/issues/167#issuecomment-419378471), however, it does not take the leading zeros and the delimiter into account, so without better option, I suggest replacing line 132 as @jones-michael-s did. I commit to #163.

**Comment by tiborauer** [comment]
Debug in #163

**Comment by jooh** [comment]
Now merged.

**Comment by tiborauer** [comment]
I have realised that there might be an issue here when using 3D NIfTIs converted from DICOM source. Converters uses hyphen to separate various iterators (e.g. series number, volume number). And that was the reason why the original code used hyphen.
Consequently, if one uses 3D NIfTIs converted from DICOM source, then it most likely have hyphen at the end. I will not break or do any harm; but the 4D filename will contain the volume number of the first non-dummy scan and a "4D" suffix. It is probably only a cosmetic issue.
