### ISSUE TITLE
aap.schema.acq_details.subjects

### ISSUE THREAD

**Issue by jpeelle** [rhodricusack/automaticanalysis#168]
After updating to the current repo (that includes the latest approved PRs) my previously-working simple script doing a BIDS import is now failing with this error:

```

Reference to non-existent field 'acq_details'.

Error in aas_addsubject (line 130)
fields=fieldnames(aap.schema.acq_details.subjects);

Error in aas_processBIDS>add_data (line 341)
    aap = aas_addsubject(aap,subjname,mriname,...

Error in aas_processBIDS (line 116)
            aap = add_data(aap,subjID,fullfile(BIDS,subjID),p,regcolumn);

Error in aa_user_ds102 (line 41)
aap = aas_processBIDS(aap);
```

because my aap.schema.acq_details does not have a "subjects" field. Following:

```
aap = aarecipe('aa_recipe.xml', 'aap_parameters_defaults.xml');
```

my aap has

```
>> aap.schema

ans = 

  struct with fields:

        tasklist: [1×1 struct]
    tasksettings: [1×1 struct]

>> 
```

I was trying to look through the history to see if aap.schema.acq_details.subjects was somehow set up in aa_recipe or via the default parametersets, but I was not able to figure this out. @jooh does any of this ring a bell? Has anyone else run into this issue?

**Comment by jooh** [comment]
That sounds bizarre. Do the non-CBU example scripts work? aa_user_demo.m?

**Comment by jpeelle** [comment]
Ok, thanks to @jones-michael-s who pointed out I had my recipe and defaults arguments switched. So this:

```
aap = aarecipe('aap_parameters_defaults.xml', 'aa_recipe.xml');
```

works great. (With the recent PR I got prompted for parameters, which before I didn't bother to specify.)
