### ISSUE TITLE
genpath( ) adds all the git hidden directories

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#169]
Like the title says. 

Here's a screen grab from aa_init:

>> reqpath =

  58×1 cell array

    {'/Users/peellelab/MSJ/automaticanalysis-msj'                               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git'                          }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/hooks'                    }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/info'                     }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/logs'                     }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/logs/refs'                }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/logs/refs/heads'          }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/logs/refs/remotes'        }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/logs/refs/remotes/origin' }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects'                  }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/0f'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/29'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/5a'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/7b'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/86'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/8a'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/9f'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/ba'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/cc'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/d6'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/d8'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/f2'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/info'             }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/objects/pack'             }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/refs'                     }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/refs/heads'               }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/refs/remotes'             }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/refs/remotes/origin'      }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/.git/refs/tags'                }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/aa_engine'                     }
    {'/Users/peellelab/MSJ/automaticanalysis-msj/aa_engine/aaq'                 }

etc...

Is this necessary? Harmless? Worth trimming?

Mike

**Comment by jpeelle** [comment]
I don't see any benefit of doing this - cleaner to ignore the .git
directory I think, unless someone objects...

**Comment by tiborauer** [comment]
👍

**Comment by jpeelle** [comment]
I see this:

aaClass.m:                rmpath(genpath(fullfile(obj.Path,'.git'))); % remove GitHub-related path

so does that mean this issue is closed @jones-michael-s ?
