### ISSUE TITLE
Warning needs to either be more informative or less frightening

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#171]
Hello all,

Apparently aamod_convert_epis now uses aas_getsetting to retrieve ignoreafter.

ignoreafter is not a parameter we've ever thought about. In fact, I didn't even know it existed. 

Until this weekend, that is. Because we now get a warning IN BIG ORANGE LETTERS:

> WARNING: Setting <ignoreafter> has fewer then 2 elements.
WARNING: First value will be applied!

This tells me precisely nothing. Is it okay to proceed with the analysis? Is it not? What?

As it stands, this warning only serves to confuse and frighten the user. 

A confused and frightened user is going to look elsewhere for his/her analysis software needs.

M

**Comment by tiborauer** [comment]
I do not mind more descriptive warning messages :)

**Comment by jones-michael-s** [comment]
I think I tend to focus more on usability because I'm not one of the original developers and so what may be obvious to others is not obvious to me. If the repo ever calms down, it'd be great to put in a serious effort into improving error messaging, parameter checking, documentation, and so on. In trying to teach aa to our students, these are the things they find really frustrating.

**Comment by jpeelle** [comment]
So maybe one action item is for each of us to try to write warning/error messages when we write code. But also, to fix those we find unhelpful (or which people we are teaching ask about). For the time being the changes have to be incremental.

**Comment by jones-michael-s** [comment]
Ok, it sound like this is a long term project. I'll close the issue.
