### ISSUE TITLE
Should there ever be a need to do file filtering on a stream contents?

### ISSUE THREAD

**Issue by rhodricusack** [rhodricusack/automaticanalysis#19]
I had imagined that a stream would uniquely identify all, and only, the files of a particular kind. So, the "structural" (or soon to be "T1") stream would only contain normalized images after normalization, and so on.

However, for the purpose of setting up bet, Sasha added the following into the structural stream during aamod_norm_noss:
- unnormalized structural 
- bias corrected structural image (mm*)
- warped structural image (w*)

Now, he and I agreed that there's no need to have the unnormalized, because if one wants, one can use the fully specified syntax in a tasklist or .xml module wrapper
<stream>aamod_copystructural.structural</stream>
to get to the previous data. So, we took this out.

However, now I'm running into a problem that the aamod_bet_modified module filters for the "mm" image, rather than taking the "w, which is what I want to run it on. By re-including file filtering within the aamod_bet_modified module, we've made it more difficult to change what a module works on by just changing its order. If you want bet to run on the data before normalization, then you put it before norm_noss; if you want it after, you put it afterwards.

I would suggest that we try to avoid file filtering for this reason. We could either write a separate bias correction module before normalization, or write this to a separate stream (T1_biascorr or something)?

**Comment by jpeelle** [comment]
Closing this issue for now but agree we should keep an eye on this issue (ongoing in issue #69).
