### ISSUE TITLE
Adding an ANTS normalisation module

### ISSUE THREAD

**Issue by alexvicegrab** [rhodricusack/automaticanalysis#26]
Hello,

I'm working on a diffeomorphic normalisation module based on ANTS:

http://picsl.upenn.edu/ANTS/ants.pdf

This will eventually be useful for region specific normalisation, as described here:
http://darwin.bio.uci.edu/~cestark/roial/roial.html

Stay tuned for new aamod_ANTS modules!

Sasha

**Comment by jpeelle** [comment]
Closed due to lack of activity.
