### ISSUE TITLE
Parallelising aa with torque

### ISSUE THREAD

**Issue by alexvicegrab** [rhodricusack/automaticanalysis#29]
I'm interested in parallelising aa by the use of torque, in order to use parallel AA at the DCCN. We can keep track of progress/issues here.

**Comment by tiborauer** [comment]
Is aacloudclient still in use?

**Comment by rhodricusack** [comment]
No!

On Monday, 20 July 2015, Tibor Auer <notifications@github.com> wrote:

> Is aacloudclient still in use?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhodricusack/automaticanalysis/issues/29#issuecomment-122904022>
> .
>


-- 
Rhodri Cusack
www.cusacklab.org

Associate Professor
Brain and Mind Institute
Natural Sciences Centre, Room 203
The University of Western Ontario
London, Ontario N6A 5B7
CANADA
+1 519 661 2111 ext 86381

**Comment by tiborauer** [comment]
Thanks! I remove then.
