### ISSUE TITLE
sliceorder stream missing

### ISSUE THREAD

**Issue by RikHenson** [rhodricusack/automaticanalysis#37]
Dear AAers -

I am trying to run a recipe for 1st-level fMRI preprocessing and stats, which looks identical to the default recipe provided with aa4 "aap_tasklist_fmri_noslicetiming_cbu32channel_withmodel.xml" (apart from an alias I added for 2 different models), but get the error below. (The same script works fine in aa3). If I don't want to do slice-time correction, how do I specify a sliceorder stream?

Thanks
Rik

You must compile the utc_time library
 AUTOMATIC ANALYSIS 31-Jul-2012 13:35:15
 =============================================================
 Parallel process ID 814724
 Current aa version 4.00 suitable for this user script

 INITIALISATION MODULE aamod_checkparameters: Check user parameters
 INITIALISATION MODULE aamod_evaluatesubjectnames: Check raw data for subject MRI:CBU120645__/_
 INITIALISATION MODULE aamod_study_init: aa initialise study
 INITIALISATION MODULE aamod_newsubj_init: Create subject directory for subject MRI:CBU120645_MR10040_CC100012/20120612_113305
 Stage aamod_get_dicom_structural input autoidentifyseries comes from aamod_autoidentifyseries_timtrio which is 1 dependencies prior
 Stage aamod_get_dicom_epi input autoidentifyseries comes from aamod_autoidentifyseries_timtrio which is 2 dependencies prior
 Stage aamod_copystructural input dicom_structural comes from aamod_get_dicom_structural which is 2 dependencies prior
 Stage aamod_convert_epis input dicom_epi comes from aamod_get_dicom_epi which is 2 dependencies prior
 Stage aamod_realign input epi comes from aamod_convert_epis which is 1 dependencies prior
 Stage aamod_tsdiffana input epi comes from aamod_realign which is 1 dependencies prior
 Stage aamod_coreg_noss input meanepi comes from aamod_realign which is 2 dependencies prior
 Stage aamod_coreg_noss input structural comes from aamod_copystructural which is 4 dependencies prior
 Stage aamod_norm_noss_cbu32channel input structural comes from aamod_coreg_noss which is 1 dependencies prior
 Stage aamod_norm_write_meanepi input normalisation_seg_sn comes from aamod_norm_noss_cbu32channel which is 1 dependencies prior
 Stage aamod_norm_write_meanepi input meanepi comes from aamod_realign which is 4 dependencies prior
 Stage aamod_norm_write input normalisation_seg_sn comes from aamod_norm_noss_cbu32channel which is 2 dependencies prior
 Stage aamod_norm_write input epi comes from aamod_realign which is 5 dependencies prior
 Stage aamod_smooth input epi comes from aamod_norm_write which is 1 dependencies prior
 Stage aamod_firstlevel_model_RTdur input epi comes from aamod_smooth which is 1 dependencies prior
 Stage aamod_firstlevel_model_RTdur input epi_header comes from aamod_convert_epis which is 8 dependencies prior

***\* automatic analysis failed - see reason and line numbers below
 Stage aamod_firstlevel_model_RTdur required input sliceorder is not an output of any stage it is dependent on. You might need to add an aas_addinitialstream command or get the stream from a remote source.
for help, see the aa wiki
??? Error using ==> aas_log at 57
aa error

Error in ==> aas_findinputstreamsources at 51
                    aas_log(aap,true,sprintf('Stage %s required input %s is not an output of any stage it is dependent on. You
                    might need to add an aas_addinitialstream command or get the stream from
Error in ==> aa_doprocessing at 159
aap=aas_findinputstreamsources(aap);

**Comment by jpeelle** [comment]
Closed due to lack of activity.
