### ISSUE TITLE
spikes and moves

### ISSUE THREAD

**Issue by rhodricusack** [rhodricusack/automaticanalysis#46]
We used to have code that inserted nuisance regressors into the first level model, to take out scans near large changes in global signal, or big movements. This used aamod_listspikes (which is in the codebase, but hasn't been updated to aa_ver4) and extra code in aamod_firstlevel_model (which looks to be missing).

Shall we put this back in? Does anyone have newer versions of the relevant code?

**Comment by jpeelle** [comment]
Closing this for now, but adding a discussion of stream conventions etc. for our next haangout as @jones-michael-s has been working on (re)implementing and extending this functionality.
