### ISSUE TITLE
Dependency problems in share-devel

### ISSUE THREAD

**Issue by alexvicegrab** [rhodricusack/automaticanalysis#47]
When I run aamod_slicetiming after aamod_realign the dependency manager loads all of the sessions (not just the current session).

The deps cell array has domain session, subject, session, session, session for these "5" streams (it loads the first session of my 4 twice)

It looks as if there is a bug in the dependency tree code, but I've not managed to find what is wrong, and don't want to break something. Could someone check/confirm this bug?

**Comment by jpeelle** [comment]
Closed - have changed development model to avoid devel vs. master branches.
