### ISSUE TITLE
devel-share: aamod_slicetiming - input .txt file not found

### ISSUE THREAD

**Issue by cmcnorgan** [rhodricusack/automaticanalysis#50]
Running aamod_slicetiming_nodicom on 2 functional runs, I find that slice timing is performed on the first run, but when the second run is attempted, I get:

/path/to/run_2/stream_epi_inputto_aamod_slicetiming_nodicom_00001.txt not found

Sure enough, the run1 directory has this text file, but the run2 directory has only aap_parameters_aamod_slicetiming_nodicom_00001.mat.

**Comment by jpeelle** [comment]
Closed - have changed development model to avoid devel vs. master branches.
