### ISSUE TITLE
aamod_norm_noss affine starting estimates

### ISSUE THREAD

**Issue by rhodricusack** [rhodricusack/automaticanalysis#55]
All of our normalizations are failing because the affine starting estimates for normalization in aamod_norm_noss.xml have changed from
< affinestartingestimate >< y >-30< /y >< z >17< /z >< pitch >0.2< /pitch >< /affinestartingestimate >
to
< affinestartingestimate ></ affinestartingestimate >

The best fix for this is to put in a little ANTs front-end to set up the starting estimate. But a workaround is to put back the values above, which were working for us.

What does everyone think?

**Comment by jpeelle** [comment]
Closed due to lack of activity (maybe future improvement would be providing the starting estimate as a stream).
