### ISSUE TITLE
Multiple files in a stream

### ISSUE THREAD

**Issue by rhodricusack** [rhodricusack/automaticanalysis#69]
I find one of the behaviours that has crept in to some of the modules (notably normalization) suboptimal.

This is that some streams - notably the structural streams, and things to do with BET - have started passing many files with different purposes. So, for example, the structural stream contains both the non-normalized (mms_) and normalized (w_) image. And the segmentation images (in some versions of the code) are output in a single "anatomical" stream.

The problem with this is that it means a module that receives this either has to do file filtering - so assuming something about the filename structure of the inputs - or rely upon the order of the files, which is opaque and could easily break.

I would suggest we revert to having all of the files within a stream being in some sense exchangeable, and use different streams to represent different kinds of data. It comes with a small extra programming overhead, but I think will save pain in the long run.

What do you all think?

**Comment by jpeelle** [comment]
Discussion May 9, 2018 (!) we agreed that streams should not contain multiple kinds of information. Specifically:

- "structural" should not change to something different after normalization (just like epi can be not normalized, or normalized)

- norm_noss modules may combine different segmentations in the "segmentation" stream which should be changed

**Comment by tiborauer** [comment]
@jpeelle, I thought we decided to drop norm_noss

Following #159, here is the list of modules and thir current behaviours:

1. checking (size(Simg,1) > 1) and setting according to settings.structural
./aamod_ANTS_build_template.m
./aamod_ANTS_struc2epi.m
./aamod_ANTS_struc2template.m
./aamod_LoAd.m
./aamod_bet.m
./aamod_bet_freesurfer.m
./aamod_bet_premask.m
./aamod_coreg_extended.m
./aamod_coreg_extended_1.m
./aamod_freesurfer_initialise.m
./aamod_fsl_FAST.m
./aamod_fsl_FIRST.m
./aamod_fsl_robustFOV.m

2. checking (size(Simg,1) > 1) and setting according to prefix (w, b)
./aamod_mask_fromstruct.m - prefix match (w, b)
./aamod_structural_overlay.m - prefix match (w)

3. checking (size(Simg,1) > 1) and using first (hard-coded)
./aamod_coreg_extended_2.m
./aamod_norm_noss.m
./aamod_pewarp_estimate.m

4. processing all according to settings.structural
./aamod_biascorrect.m 
./aamod_biascorrect_ANTS.m
./aamod_denoiseANLM.m

I am happy to edit all to omit any checking and settings and make them expect only one file.

**Comment by jpeelle** [comment]
I believe we did decide to drop norm_noss.
