### ISSUE TITLE
Freesurfer module - "no inputs" error

### ISSUE THREAD

**Issue by nicofarr** [rhodricusack/automaticanalysis#71]
Hi, 

I'm tyring to run the freesurfer pipeline (default setup : -recon_all), I based my user script on aa_user_FS.m . It crashes when attempting to run aamod_freesurfer_reconall with the following error (although the aamod_freesurfer_initialize passed) . Did I miss anything ? Should there be any more parameters in the user script ? 

All the best, 

***\* automatic analysis failed - see reason and line numbers below
No inputs obtained for stream freesurfer
for help, see the aa wiki
Error using aas_log (line 58)
aa error

Error in aa_doprocessing_onetask (line 106)
                        aas_log(aap,true,sprintf('No
                        inputs obtained for
                        stream %s',inp.name));

**Comment by jpeelle** [comment]
We think this is now fixed.
