### ISSUE TITLE
SPM12

### ISSUE THREAD

**Issue by tiborauer** [rhodricusack/automaticanalysis#76]
Shall we move onto SPM12 as a default recommeded for aa?
I had a discussion with Guillaume Flandin and most of our spm_mods are/will be incorporated in SPM12 but not in SPM8. here is Guillaume's message:

many thanks for sharing this - this is very useful. I'm detailing below what I understood the modifications were for each file and their status in SPM. As you might notice, I often refer to SPM12 - that's because SPM8 is in a dead-end now and we won't add new features to it. I would strongly recommend that you have a look at SPM12 and see how all of your developments work with it - we tried to make it backward compatible as much as possible so if you were to encounter any problem, that would be useful information to us.
- spm_run_realignunwarp.m
  => Handle 4D data
  This was fixed in r5644 in SPM12 last September.
- FieldMap_create.m
  => Handle 4D data (?)
  In theory, the field "Select EPI to Unwarp" expects a single frame (epi.filter = 'image'; and epi.num = [1 1]; in tbx_cfg_fieldmap.m).
  so there shouldn't be a problem there with 4D data. Unless dependencies are used without using "Expand image frames" first or that the batch is set up in a script that doesn't add the trailing ',1' for that entry as it should be. When does it happen for you?
- spm_dicom_convert.m
  => Handle Siemens 7T data (?)
  According to a diff, the only change is this:
  
  >   if i == 2 && j == 1
  >       warning('We assume the ICE dims are identical to account for the 7T scanner import to work [alevic]')
  >   end
  >   identical_ice_dims = 1;
  > Given that it forces identical_ice_dims to be 1 in all situations, I cannot make this change. I would need an example of DICOM data that SPM don't convert properly automatically, and, if a fix has to be made to the code, it should only take place with these sorts of data by finding a setting that detects them uniquely.
- spm_render.m
  => Add output variable to get RGB images.
  I modified spm_render in SPM12 so that the rendered images are available as RGB images in a cell array. If no display is available, the function will still run through (headless mode). There is still something to sort out with the global variable prevrend, but you can still call spm_render after manually setting the variable if you want to call the function programmatically.
- spm_spm_saveresids.m
  => Provide access to the residuals.
  The temporary files ResI\* are _normalised_ residuals used for smoothness estimation and, by default, are only a subset of all residuals images.
  In SPM12, the option to save the residuals is explicitly available when estimating a GLM ("Write residuals?", Yes/[No]). This is implemented in a separate function spm_write_residuals.m (this requires an extra pass on the data but makes it unrelated to RFT, and you also have an option to filter out data by specifying an F-contrast).
- spm_coreg.m / spm_hist2.m
  => Add the option to use a weighting volume when computing the joint histogram during coregistration.
  Do you know the circumstances under which this option is useful? If it were to be added, I guess it would be better to modify the spm_hist2.c file unless the MATLAB version is now faster than the C equivalent.

**Comment by jpeelle** [comment]
Closing this - everyone should be defaulting with SPM12. Where there are version difficulties we should try to check and/or notify users.
