### ISSUE TITLE
Avoiding eval()

### ISSUE THREAD

**Issue by conorwild** [rhodricusack/automaticanalysis#78]
Hi all,

Could we please avoid using Matlab's eval() function - especially in the core engine scripts? This function prevents the script from being compiled, which is required for parallel computing via Condor.

Thanks!

PS I fixed the recent change to aas_getfiles_bystream() to get rid of this call.

**Comment by tiborauer** [comment]
I have removed eval() from our code, wherever it was possible.

However, there are still a few left:
- [ ] `aa_modules/aamod_compSignal.m` and `aa_modules/aamod_compSignal_nobet.m` were written by someone else and it was hard for me to decipher the code.

- [ ] There are som external functions. Some of them can be "convereted" easily
  - external/MFP/mw_mfp.m
  - external/TFCE/cg_tfce_update.m
  - external/TFCE/cg_tfce_update.m
  - external/vbm8/cg_vbm8_batch.m
  - external/vbm8/cg_vbm8_run.m
  - external/vbm8/cg_vbm8_update.m
  - external/XML_IO_Tools/gen_object_display.m
 Some of them are harder to convert:
  - external/jsonlab/loadjson.m
  - external/cprintf.m
  - external/vbm8/cg_slice_overlay.m
  - external/vbm8/cg_spm8_batch.m
  - external/vbm8/checkinopt.m
  - external/vbm8/slice_overlay.m
 The question is whether we want to modify them likely rendering furher update much harder.

**Comment by tiborauer** [comment]
Besides, I have just found [this link](http://blogs.mathworks.com/loren/2008/06/19/writing-deployable-code/#18). I wonder whether it may help in cases when avioding eval may be too complicated.

**Comment by alexvicegrab** [comment]
I wrote compSignal a while ago, based on some code at the Donders. The one
line that needs conversion is line 90:

for m = 1:size(SMimg,1)
            % The ones *not* including string 'rwc' are the native masks
            [junk,fn] = fileparts(SMimg(m,:));
            if isempty(strfind(fn, 'rwc'))
                indx = strfind(fn, 'rc');
                eval(['m' MOlist{str2num(fn(indx + 2))} ' =
spm_read_vols(spm_vol(SMimg(m,:)));'])
            end
        end

This creates variables on the fly, most probably can be substituted with a
few lines more or less like this (but note: *I DO NOT remember if the order
is correct*):

mGM = spm_read_vols(spm_vol(SMimg(1,:)));
mWM = spm_read_vols(spm_vol(SMimg(2,:)));
mCSF = spm_read_vols(spm_vol(SMimg(3,:)));

It's hard to test over here as I don't have MATLAB anymore but it should
not be too hard to change.

Hope it helps a little bit!
Sasha

On 3 August 2015 at 14:38, Tibor Auer <notifications@github.com> wrote:

> I have removed eval() from our code, wherever it was possible.
>
> However, there are still a few left:
>
>    -
>
>    aa_modules/aamod_compSignal.m and aa_modules/aamod_compSignal_nobet.m
>    were written by someone else and it was hard for me to decipher the code.
>    -
>
>    There are som external functions. Some of them can be "convereted"
>    easily
>    - external/MFP/mw_mfp.m
>       - external/TFCE/cg_tfce_update.m
>       - external/TFCE/cg_tfce_update.m
>       - external/vbm8/cg_vbm8_batch.m
>       - external/vbm8/cg_vbm8_run.m
>       - external/vbm8/cg_vbm8_update.m
>       - external/XML_IO_Tools/gen_object_display.m Some of them are
>       harder to convert:
>       - external/jsonlab/loadjson.m
>       - external/cprintf.m
>       - external/vbm8/cg_slice_overlay.m
>       - external/vbm8/cg_spm8_batch.m
>       - external/vbm8/checkinopt.m
>       - external/vbm8/slice_overlay.m The question is whether we want to
>       modify them likely rendering furher update much harder.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhodricusack/automaticanalysis/issues/78#issuecomment-127219209>
> .
>



-- 
Vicente Grabovetsky, Alejandro (Sasha)
Entrepreneur, PhD
uk.linkedin.com/in/sashavg

**Comment by tiborauer** [comment]
I have made the minimum change:
replacing 
`eval(['m' MOlist{str2num(fn(indx + 2))} ' = spm_read_vols(spm_vol(SMimg(m,:)));'])`
with
`assignin('caller',['m' MOlist{str2num(fn(indx + 2))}],spm_read_vols(spm_vol(SMimg(m,:))));`

**Comment by jpeelle** [comment]
Closing this issue as we (I believe) have working compiled scripts. Of course it's worth keeping this restriction in mind going forward.
