### ISSUE TITLE
SPM paths

### ISSUE THREAD

**Issue by rhodricusack** [rhodricusack/automaticanalysis#80]
Lots of paths are now added by a call to a function aa_init at the start of aa_doprocessing, including the spm path gathered from aap.directory_conventions.spmdir, eeglab, and many other things. This overrides the previous behaviour, which was only to add spm if it wasn't already in path (aas_checkspmrunning). 

I can see the utility of controlling the paths added more vigorously, but it generates a problem. I sometimes like to override components of SPM, EEGLAB or whatever for a specific project. I don't want to add anything to the "extrafunctions/spm_mods" as they're not relevant to all projects, or not yet tested. Previously, it was possible to add paths above SPM (like the directory containing the user script) and they would stay dominant. Now, as SPM gets added at the start of every run, they get overridden.

How should we solve this? Perhaps by always adding the user script directory above SPM. And/or allowing customization of the spm_mods paths?

**Comment by conorwild** [comment]
Also, I have noticed lately that aa_init takes anywhere from 5-15 seconds to run - which feels long when I am debugging an analysis and have to restart it many times. It seems rather inefficient to be searching and adding paths every time we start an analysis; wouldn't this be more appropriate to do once per session? Maybe it would be better to do this in aa_ver4 (and/or aa_ver4_nocloud) scripts when we add the aa paths?

**Comment by tiborauer** [comment]
I wanted to make it sure that required path is added (aa_init) before and cleared (aa_close) after analysis.
There are two options:
1. Robustness: (present) aa_init and aa_close are in aa_doprocessing: It may increase the time for debugging, but it requires no changes in the UMS
2. Time: aa_init and aa_close are part of UMS: It eliminates redundancy but gives the control (and chance to error) to the user.

**Comment by tiborauer** [comment]
Is there anyone using spm_spm_saveresids.m in spm_mods?
I detected a modue called aamod_modelestimate.

aamod_firstlevelmodel with SPM12 already supports writing residuals (see setting "writeresiduals").

**Comment by tiborauer** [comment]
All spm_mods (apart from spm_spm_saveresids.m) will be included in the next SPM12 update, so we may be able to get rid of the spm_mods.

**Comment by jpeelle** [comment]
Is this issue worth revisiting, or can we close (for now)? @tiborauer

**Comment by tiborauer** [comment]
I am, obviously, happy with the current behaviour. :)

**Comment by jooh** [comment]
Closing for now - @rhodricusack, feel free to re-open if you want to see further changes here.

Personally, I think it's good to attempt some kind of parity between what is on the path in qsub and localsingle mode, and Tibor's solution goes some way in that direction.
