### ISSUE TITLE
aamod_bet_diffusion

### ISSUE THREAD

**Issue by giuseppecabras** [rhodricusack/automaticanalysis#83]
Hi there,
in aap_tasklist_diffusion.xml you have an aamod_bet_diffusion which is missing, I assume it is the existing aamod_diffusion_bet.
Best,
Giuseppe

**Comment by rhodricusack** [comment]
Giuseppe
Apologies, it was missing. I've added it (its just an xml wrapper, pointing
to aamod_bet)
Best,
Rhodri


On 8 April 2015 at 08:53, Giuseppe Cabras <notifications@github.com> wrote:

> Hi there,
> in aap_tasklist_diffusion.xml you have an aamod_bet_diffusion which is
> missing, I assume it is the existing aamod_diffusion_bet.
> Best,
> Giuseppe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhodricusack/automaticanalysis/issues/83>.
>



-- 
Rhodri Cusack
www.cusacklab.org

Associate Professor
Brain and Mind Institute
Natural Sciences Centre, Room 203
The University of Western Ontario
London, Ontario N6A 5B7
CANADA
+1 519 661 2111 ext 86381

**Comment by tiborauer** [comment]
We have changed the convention, using the modality name first (i.e. aamod_diffusion_bet).

Vale,

Auer, Tibor M.D. Ph.D.
MRC Cognition and Brain Sciences Unit
15 Chaucer Road
Cambridge
CB2 7EF
United Kingdom
Phone/Work: +44-(0)1223-273613
Mail: Tibor.Auer@mrc-cbu.cam.ac.uk
________________________________________
Felad�: rhodricusack [notifications@github.com]
K�ldve: 2015. �prilis 8. 14:11
C�mzett: rhodricusack/automaticanalysis
T�rgy: Re: [automaticanalysis] aamod_bet_diffusion (#83)

Giuseppe
Apologies, it was missing. I've added it (its just an xml wrapper, pointing
to aamod_bet)
Best,
Rhodri


On 8 April 2015 at 08:53, Giuseppe Cabras <notifications@github.com> wrote:

> Hi there,
> in aap_tasklist_diffusion.xml you have an aamod_bet_diffusion which is
> missing, I assume it is the existing aamod_diffusion_bet.
> Best,
> Giuseppe
>
> �
> Reply to this email directly or view it on GitHub
> <https://github.com/rhodricusack/automaticanalysis/issues/83>.
>



--
Rhodri Cusack
www.cusacklab.org

Associate Professor
Brain and Mind Institute
Natural Sciences Centre, Room 203
The University of Western Ontario
London, Ontario N6A 5B7
CANADA
+1 519 661 2111 ext 86381

�

**Comment by giuseppecabras** [comment]
Thanks Rhodri and Vale,
by the way, I am trying to do DTI from nifti, to do this I have added:
aas_addinitialstream for bvecs,bvals,diffusion_data and structural
and removed from the recipe, at the beginning of the main section:
            <module><name>aamod_autoidentifyseries_timtrio</name></module>
            <module><name>aamod_get_dicom_diffusion</name></module>
            <module><name>aamod_convert_diffusion</name></module>

but then, when I run it, I get the error:

MODULE aamod_3dto4d_diffusion RUNNING: Convert 3d diffusion to 4d file for /home/gc/AAdev/DTIexample1/dti_analysis/aamod_3dto4d_diffusion_00001/PUD400614/DTI
 retrieve stream diffusion_data from /home/gc/AAdev/DTIexample1/dti_analysis/aamod_importfilesasstream_00003/PUD400614 to /home/gc/AAdev/DTIexample1/dti_analysis/aamod_3dto4d_diffusion_00001/PUD400614
 executing


**** automatic analysis failed - see reason and line numbers below
Attempting to load stream from file /home/gc/AAdev/DTIexample1/dti_analysis/aamod_3dto4d_diffusion_00001/PUD400614/DTI/stream_diffusion_data_outputfrom_aamod_3dto4d_diffusion_00001.txt, but not found
for help, see the aa wiki

... I think I must do something more then just remove the DICOM modules from the recipe.
Have you any example for that?

Best,
Giuseppe

**Comment by tiborauer** [comment]
For diffusion, I have recently written a aamod_diffusionfromnifti and modified the aas_addsubjetc, so you can specify the data as a structure with fields 'fname' (path to image), and 'bval', 'bvec' (path to bvals and bvecs).
You should of course, remove any DICOM-related modules from the tasklist.

**Comment by tiborauer** [comment]
Shall we close this?
