### ISSUE TITLE
mvpaamailer

### ISSUE THREAD

**Issue by alexvicegrab** [rhodricusack/automaticanalysis#85]
Since I set up mvpaamailer when I was back in Cambs, the security @ gmail has been increased and now it blocks attempts to use the mailer when not in UK.

People who want to use the mailer service outside UK will probably have to set up their own mailer accounts as 2 step verification is probably not an option.

**Comment by jpeelle** [comment]
Setting in aap to customize mailer options (which should be set for each site).
