### ISSUE TITLE
mutliple DICOM sources

### ISSUE THREAD

**Issue by tiborauer** [rhodricusack/automaticanalysis#90]
Is there a way to specify multiple DICO sources for a subject?
I am considering introducing a `subjname` field within `aap.acq_details.subject` to distangle mriname from subject name, so mriname can be a cell with multiple entries.

**Comment by rhodricusack** [comment]
Sounds interesting, but can you make it backwards compatible so that old
aap structures, or user scripts that set mriname directly still work?

On Thu, Dec 3, 2015, 6:49 AM Tibor Auer <notifications@github.com> wrote:

> Is there a way to specify multiple DICO sources for a subject?
> I considering introducing a subjname field within aap.acq_details.subject
> to distangle mriname from subject name, so mriname can be a cell with
> multiple entries.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhodricusack/automaticanalysis/issues/90>.
>
-- 
Principal Investigator, Brain and Mind Institute
Associate Professor, Departments of Psychology, Medical Biophysics and
Medical Imaging
Western University, Canada

**Comment by tiborauer** [comment]
I am working on it! :)
I refine the interpretation of `aap.directory_conventions.subject_directory_format`: 
0-3 -> from subject_directory_names | from data | S# | manual
So, "1" would mean that `subjname` is generated from `mriname` or `megname` (whichever is first in the second input of aas_adddata - as usual). In case of multiple `mriname` (i.e. multiple DICOM source), the first will be used.

**Comment by tiborauer** [comment]
I also adapt the engine and modules referring to `mriname`, so they will use 'subjname' instead. However, it means that older aap_parameter.mat structures, will not be compatible with the new version. So I am also considering to change version --> aa 5

**Comment by tiborauer** [comment]
I will not commit those changes with this branch now.

**Comment by rhodricusack** [comment]
Are you sure we can't  do this without changing all the modules,  or at
least making them backwards compatible? This will cause a lot of chaos to
accommodate quite a rare circumstance??

On Thu, Dec 3, 2015, 10:08 AM Tibor Auer <notifications@github.com> wrote:

> I will not commit those changes with this branch now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhodricusack/automaticanalysis/issues/90#issuecomment-161668999>
> .
>
-- 
Principal Investigator, Brain and Mind Institute
Associate Professor, Departments of Psychology, Medical Biophysics and
Medical Imaging
Western University, Canada

**Comment by tiborauer** [comment]
That is why I would rather start a new branch. 
Some of the modules (and engine) uses `mriname`. And I think we have to separate the analysis from `mriname`, once data is imported. 

This backward incompatibility is only an issue, if someone wants to use 'low-level' functions (i.e. without the engine), especially if they want to use the 'stage-specific' (i.e. in the subfolder of the modules) aap_parameter.mat files. If they run `aa_doprocessing` or just `aas_doprocessing_initialisationmodules` (i.e. `aamod_evaluatesubjectnames`), it will add subjname to the structure if not present. So that 'updated' `aap` can be used even with the 'low-level' functions.

For 'low-level' backward compatibility, one option would be to let every affected function continue using `mriname` is `subjname` is not present. The question is that how important to ensure the 'low-level' backward compatibility.

**Comment by rhodricusack** [comment]
Why not just reverse the logic, by adding a field "dicomname" that
overrides mriname as the source of dicoms, in the circumstance it isn't
empty. Then only one module would need to be changed?

On Thu, 3 Dec 2015 at 13:01 Tibor Auer <notifications@github.com> wrote:

> That is why I would rather start a new branch.
> Some of the modules (and engine) uses mriname. And I think we have to
> separate the analysis from mriname, once data is imported.
>
> This backward incompatibility is only an issue, if someone wants to use
> 'low-level' functions (i.e. without the engine), especially if they want to
> use the 'stage-specific' (i.e. in the subfolder of the modules)
> aap_parameter.mat files. If they run aa_doprocessing or just
> aas_doprocessing_initialisationmodules (i.e. aamod_evaluatesubjectnames),
> it will add subjname to the structure if not present. So that 'updated'
> aap can be used even with the 'low-level' functions.
>
> For 'low-level' backward compatibility, one option would be to let every
> affected function continue using mriname is subjname is not present. The
> question is that how important to ensure the 'low-level' backward
> compatibility.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhodricusack/automaticanalysis/issues/90#issuecomment-161733365>
> .
>
-- 
Principal Investigator, Brain and Mind Institute
Associate Professor, Departments of Psychology, Medical Biophysics and
Medical Imaging
Western University, Canada

**Comment by tiborauer** [comment]
That could work. I have not thought about that because I wanted to keep using `mriname` and `megname` in a same way (i.e. as defining sources). With your "reversed" idea, `mriname` would be a subject name and `dicomname` would be the source descriptor; which is OK for most cases; however, when MEG is (also) present, then `megname` would be a subject name (and MEG source descriptor) and `mriname` would be the MRI source descriptor. Just like now.
I just thought, it would be more consitent to have a single `subjname` regardless of modality and `mriname` and `megname`  would be source descriptors accordingly. And to ensure the present practice, when `aap.directory_conventions.subject_directory_format` is 1, then 'subjname` is determined from `mriname` or `megname` accordingly.

Besides, even with your idea, it would not be juts one module but several files of the engine (e.g. aas_addsubject, mri_findvol, ass_findvol) and the corresponding modules (aamod_evaluatesubjectname, aamod_autoidentifyseries, aamod_get_dicom_*).

**Comment by rhodricusack** [comment]
I think changing the most common purpose of mriname is going to cause chaos
- it appears at 79 places in our github code, and presumably in hundreds
more, in people's local customized scripts. I would be strongly in favour
of a more backwards compatible solution, even if it is a little less
elegant. My impression is that those early DICOM convert stages are
customized much less often - I don't remember ever doing it - but even
those changes could be made backwards compatible quite easily?

On Thu, 3 Dec 2015 at 13:24 Tibor Auer <notifications@github.com> wrote:

> That could work. I have not thought about that because I wanted to keep
> using mriname and megname in a same way (i.e. as defining sources). With
> your "reversed" idea, mriname would be a subject name and dicomname would
> be the source descriptor; which is OK for most cases; however, when MEG is
> (also) present, then megname would be a subject name (and MEG source
> descriptor) and mriname would be the MRI source descriptor. Just like now.
> I just thought, it would be more consitent to have a single subjname
> regardless of modality and mriname and megname would be source
> descriptors accordingly. And to ensure the present practice, when
> aap.directory_conventions.subject_directory_format is 1, then 'subjnameis
> determined frommrinameormegname` accordingly.
>
> Besides, even with your idea, it would not be juts one module but several
> files of the engine (e.g. aas_addsubject, mri_findvol, ass_findvol) and the
> corresponding modules (aamod_evaluatesubjectname, aamod_autoidentifyseries,
> aamod_get_dicom_*).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhodricusack/automaticanalysis/issues/90#issuecomment-161738758>
> .
>
-- 
Principal Investigator, Brain and Mind Institute
Associate Professor, Departments of Psychology, Medical Biophysics and
Medical Imaging
Western University, Canada

**Comment by tiborauer** [comment]
I know, believe me. I went through all of them. :)
And what do we do, when we want to support multiple MEG sources? Do we create a new field called `fifname`? And how about physiological recording? And what do we do if we want to combine them? So far we used structural MRI only to aid MEG/EEG, so it is obvious that the "subjname" comes from `megname`. But how do we chose if we want to combine MEG/EEG and fMRI? Which one will we use as "subjname"?
I feel that it is an issue we have to deal with sooner a later; and we need a robust long-term solution. Especially, if we want aa to be a "product" rather than an internal collection of scripts.

I can probably provide a "converter", which scans through `subjects` within the `acq_details`, and add `subjname`.

It is a major change. That is why I am also a bit hesitant.
I already modified the DICOM converter stage to capture slice times and other timing informations from the header to allow automatic slicetiming and fieldmap correction. 
Another mid-size change in the near future will be also needed to move fieldmaps from subject domain to session domain, or at least, allow session-specific fieldmaps. Because it is not (always) appropriate to assume that fieldmap does not change from session to session. If one uses AutoAlign (from Siemens) to minimize between-session displacement (now standard in CBSU), it also reshims, so the fieldmap is not valid anymore. And even if you do not use it, subjects may move quite a lot between session to "stretch out", so the field also changes. But it may require another "issue" to open.

**Comment by tiborauer** [comment]
Another advantage of using a separate `subjname` is, that is simplifies referring to subjects in the UMS. There are modules storing subject-specific settings (e.g. events, covariates, contrasts, affine starting transformations, subjects to exclude from dartel template creation). Using `mriname` is ambiguous, because it is not clear whether the specification and identification of the subjects uses unprocessed or evaluated `mriname`. Most times, the user has to pre-evaluate `mriname` in the script. Using `subjname` would make the specification and identification of the subjects unambiguous.

**Comment by tiborauer** [comment]
It is a bigger issue in backward-compatibility that the subject structure must be changed. It is not enough to provide multiple mrinames/dicomnames but also multiple entries for the series numbers, to specify which series of which source will be analyzed.

**Comment by tiborauer** [comment]
Implemented in branch v5.
