### ISSUE TITLE
How to analyze the Longitudinal data using aa_5

### ISSUE THREAD

**Issue by gr8zhuzc** [rhodricusack/automaticanalysis#93]
Hi,

I am working in Jonathan Peelle's lab. 
Now I want to analyze fMRI imaging data from a single subject in different days. I saw that the longitudinal measurement has been added to the aa version 5 in the change log. But I can't find more details either on the website or the discussion forum. Could you please describe or give an example of how to analyze the longitudinal data in the user script?

Thank you very much.
Zhenchen

**Comment by tiborauer** [comment]
https://github.com/rhodricusack/automaticanalysis/blob/v5-stable/examples/aa_user_fmri_multi.m
