### ISSUE TITLE
delete github wiki?

### ISSUE THREAD

**Issue by jooh** [rhodricusack/automaticanalysis#95]
The AA manual on the Github wiki is out of date. Are there any objections to deleting this content and replacing with a link to automaticanalysis.org? I'm planning to do something similar with the AA content on the imaging wiki (except for the CBU-specific stuff). Helps stop new users from getting their information from the wrong place.

**Comment by tiborauer** [comment]
I do not mind either.

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D2338B.1F3C9360] +44-1784-27-6594
[cid:image002.jpg@01D2338B.1F3C9360] Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>

[royalhollowaylogo]<https://www.royalholloway.ac.uk/psychology/home.aspx>

**Comment by jooh** [comment]
Done.
