### ISSUE TITLE
Modeling for VBM?

### ISSUE THREAD

**Issue by jones-michael-s** [rhodricusack/automaticanalysis#96]
Hello all,

We’re currently trying to do VBM, using Dartel to map multiple subjects into MNI space. I’ve got the preprocessing working, but I’m stuck on setting up the GLM.

I believe it’s a simple matter of getting aa to use the normed & smoothed structural images as the contrast maps in a second level analysis. I can make this happen in SPM, but so far no luck with aa. Specifically, aa_secondlevel_mod  takes firstlevel_spm and firstlevel_cons as input streams, and these are generated by aamod_firstlevel_model and  aamod_firstlevel_contrasts. The first level modules only take epi for input. 

Is there a simple workaround? Renaming streams? Doing a multiple subject 1st level design? I’m probably making this harder than it is, but I just can’t figure it out from the docs.

Thanks for any help,
Mike

**Comment by jpeelle** [comment]
My quick look at the modules suggests no existing second level model for structural images. Can anyone (Tibor, Johan) confirm this is correct? If so, we will create one.

**Comment by tiborauer** [comment]
I am not aware of any such module. However, I do not think we have to create a new modukle (i.e. writing code), but creating a new header pointing to aamod_secondlevel_model can do the trick.

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D04F5F.0CADAB60]+44-1784-27-6594
[cid:image002.jpg@01D04F5F.0CADAB60]Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>
[Email signature]
