### ISSUE TITLE
Remove deprecated modules

### ISSUE THREAD

**Issue by jooh** [rhodricusack/automaticanalysis#97]
Going through aa_modules, there are more than a few that are no longer supported (and which no longer work). Two examples would be aamod_firstlevel_modelspecify and aamod_autoidentifyseries. To avoid confusion for new users, it would be better if these were removed in the next release.

If we ever want to repair them and bring them back they remain available in the git version history of course.

If you know of any other modules that are probably no longer supported, maybe let us know in comments and we can do a big cleanup commit once we've converged.

**Comment by tiborauer** [comment]
*   aamod_coreg_extended_2/settings/structural
     *   aamod_highpass vs. aamod_highpassfilter_epi
     *   aamod_firstlevel_modelspecify and aamod_firstlevel_modelestimate
     *   Unconverted/orphan (without xml) modules:
        *   aamod_imcalc
        *   aamod_mirrorandsubtract
        *   aamod_ppi_model

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham Hill
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D04F5F.0CADAB60] +44-1784-27-6594
[cid:image002.jpg@01D04F5F.0CADAB60] Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>

[royalhollowaylogo]<https://www.royalholloway.ac.uk/psychology/home.aspx>

**Comment by jpeelle** [comment]
Deleting:

	deleted:    aamod_firstlevel_modelestimate.xml
	deleted:    aamod_firstlevel_modelspecify.m
	deleted:    aamod_firstlevel_modelspecify.xml
	deleted:    aamod_imcalc.m
	deleted:    aamod_mirrorandsubtract.m
	deleted:    aamod_ppi_model.m

and closing the issue, but reminding us that we should return to this periodically (we still have lots of deprecated modules!).
