### ISSUE TITLE
Physiological Noise Correction

### ISSUE THREAD

**Issue by NADRIGOL** [rhodricusack/automaticanalysis#98]
Hello all,

Are there currently any modules for physiological noise correction? Something like AFNI's RETROICOR, FSL's PNM, or TAPAS's PhysIO Toolbox?

Thanks

**Comment by tiborauer** [comment]
Hi,

I am not aware of any.

Vale,
Tibor

Auer, Tibor M.D. Ph.D.
Research Fellow in MRI
Department of Psychology
Royal Holloway University of London
Egham
TW20 0EX
United Kingdom
[cid:image001.jpg@01D04F5F.0CADAB60]+44-1784-27-6594
[cid:image002.jpg@01D04F5F.0CADAB60]Tibor.Auer@rhul.ac.uk<mailto:Tibor.Auer@rhul.ac.uk>
[Email signature]
